version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-processor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pa8ajudgn2mh"
s3_prefix = "lambda-processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaSize=\"1024\""
